"""Implementar sistema de temas y feedback de clientes

Revision ID: 0bdfde74f9a1
Revises: b5dc708819c0
Create Date: 2025-09-08 17:44:21.281143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdfde74f9a1'
down_revision: Union[str, Sequence[str], None] = 'b5dc708819c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('es_premium', sa.Boolean(), nullable=False),
    sa.Column('url_vista_previa_dark', sa.String(length=255), nullable=True),
    sa.Column('url_vista_previa_light', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_temas_id'), 'temas', ['id'], unique=False)
    op.create_table('variables_css_tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('nombre_variable', sa.String(length=50), nullable=False),
    sa.Column('valor_dark', sa.String(length=50), nullable=False),
    sa.Column('valor_light', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tema_id'], ['temas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variables_css_tema_id'), 'variables_css_tema', ['id'], unique=False)
    op.create_table('feedback_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('QUEJA', 'SUGERENCIA', 'FELICITACION', name='tipofeedback'), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('contacto_cliente', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_cliente_id'), 'feedback_cliente', ['id'], unique=False)
    op.add_column('negocios', sa.Column('tema_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'negocios', 'temas', ['tema_id'], ['id'])
    op.drop_column('negocios', 'color_primario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negocios', sa.Column('color_primario', sa.VARCHAR(length=7), server_default=sa.text("'#3B82F6'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'negocios', type_='foreignkey')
    op.drop_column('negocios', 'tema_id')
    op.drop_index(op.f('ix_feedback_cliente_id'), table_name='feedback_cliente')
    op.drop_table('feedback_cliente')
    op.drop_index(op.f('ix_variables_css_tema_id'), table_name='variables_css_tema')
    op.drop_table('variables_css_tema')
    op.drop_index(op.f('ix_temas_id'), table_name='temas')
    op.drop_table('temas')
    # ### end Alembic commands ###
