"""Añadir alias_cliente a pedidos

Revision ID: 4201516563af
Revises: c23f33348279
Create Date: 2025-09-13 14:13:25.954809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4201516563af'
down_revision: Union[str, Sequence[str], None] = 'c23f33348279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_categoria_negocio'), 'categorias', type_='unique')
    op.add_column('pedidos', sa.Column('alias_cliente', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('uq_producto_negocio'), 'productos', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_producto_negocio'), 'productos', ['nombre', 'negocio_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('pedidos', 'alias_cliente')
    op.create_unique_constraint(op.f('uq_categoria_negocio'), 'categorias', ['nombre', 'negocio_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
