"""Añadir relación faltante de cuenta a mesa

Revision ID: 76a3a9e9d6ad
Revises: 0bdfde74f9a1
Create Date: 2025-09-10 14:08:19.410782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a3a9e9d6ad'
down_revision: Union[str, Sequence[str], None] = '0bdfde74f9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
