"""Crear estructura de base de datos completa desde cero

Revision ID: c23f33348279
Revises: 
Create Date: 2025-09-12 15:20:54.795621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23f33348279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_codigo'), 'permisos', ['codigo'], unique=True)
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('temas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('es_premium', sa.Boolean(), nullable=False),
    sa.Column('url_vista_previa_dark', sa.String(length=255), nullable=True),
    sa.Column('url_vista_previa_light', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_temas_id'), 'temas', ['id'], unique=False)
    op.create_table('negocios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=255), nullable=True),
    sa.Column('marca_origen', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('modo_cobro', sa.String(length=20), server_default='POSTPAGO', nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tema_id'], ['temas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negocios_id'), 'negocios', ['id'], unique=False)
    op.create_index(op.f('ix_negocios_ruc'), 'negocios', ['ruc'], unique=True)
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('variables_css_tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('nombre_variable', sa.String(length=50), nullable=False),
    sa.Column('valor_dark', sa.String(length=50), nullable=False),
    sa.Column('valor_light', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tema_id'], ['temas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variables_css_tema_id'), 'variables_css_tema', ['id'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=False)
    op.create_table('centros_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_produccion_id'), 'centros_produccion', ['id'], unique=False)
    op.create_table('grupos_modificadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('seleccion_minima', sa.Integer(), nullable=False),
    sa.Column('seleccion_maxima', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_modificadores_id'), 'grupos_modificadores', ['id'], unique=False)
    op.create_table('locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locales_id'), 'locales', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_table('metodos_pago_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('nombre_metodo', sa.String(length=50), nullable=False),
    sa.Column('datos_adicionales', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodos_pago_local_id'), 'metodos_pago_local', ['id'], unique=False)
    op.create_table('opciones_modificadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio_extra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_modificadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opciones_modificadores_id'), 'opciones_modificadores', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('tipo_producto', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tiene_variantes', sa.Boolean(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('centro_produccion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['centro_produccion_id'], ['centros_produccion.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('sueldo_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('password_hashed', sa.String(length=255), nullable=False),
    sa.Column('reset_password_token', sa.String(length=10), nullable=True),
    sa.Column('reset_password_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=True),
    sa.Column('local_asignado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['local_asignado_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_numero_documento'), 'usuarios', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_usuarios_telefono'), 'usuarios', ['telefono'], unique=True)
    op.create_index(op.f('ix_usuarios_tipo_documento'), 'usuarios', ['tipo_documento'], unique=False)
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zonas_id'), 'zonas', ['id'], unique=False)
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_o_numero', sa.String(length=50), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesas_id'), 'mesas', ['id'], unique=False)
    op.create_table('producto_grupo_modificador',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('grupo_modificador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_modificador_id'], ['grupos_modificadores.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'grupo_modificador_id')
    )
    op.create_table('producto_locales',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('precio_local', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'local_id')
    )
    op.create_table('variantes_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'nombre', name='_producto_variante_uc')
    )
    op.create_index(op.f('ix_variantes_producto_id'), 'variantes_producto', ['id'], unique=False)
    op.create_index(op.f('ix_variantes_producto_sku'), 'variantes_producto', ['sku'], unique=True)
    op.create_table('cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('usuario_cliente_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTA', 'CERRADA', 'PAGADA', 'CANCELADA', name='estadocuenta'), nullable=False),
    sa.Column('total_calculado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('propina', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['usuario_cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_id'), 'cuentas', ['id'], unique=False)
    op.create_table('feedback_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('QUEJA', 'SUGERENCIA', 'FELICITACION', name='tipofeedback'), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('contacto_cliente', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_cliente_id'), 'feedback_cliente', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('mozo_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('total_pedido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE_DE_PAGO', 'PENDIENTE', 'EN_PREPARACION', 'LISTO_PARA_RECOGER', 'COMPLETADO', 'CANCELADO', name='estadopedido'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['mozo_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('medio_de_pago', sa.Enum('TARJETA_CREDITO', 'TARJETA_DEBITO', 'YAPE', 'PLIN', 'EFECTIVO', 'OTRO', name='mediodepago'), nullable=False),
    sa.Column('estado', sa.Enum('EXITOSA', 'FALLIDA', 'PENDIENTE', name='estadotransaccion'), nullable=False),
    sa.Column('referencia_externa', sa.String(length=255), nullable=True),
    sa.Column('fecha_transaccion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacciones_id'), 'transacciones', ['id'], unique=False)
    op.create_table('detalles_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nombre_producto', sa.String(), nullable=False),
    sa.Column('nombre_variante', sa.String(), nullable=True),
    sa.Column('nota_cocina', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_pedido_id'), 'detalles_pedido', ['id'], unique=False)
    op.create_table('detalle_pedido_modificadores',
    sa.Column('detalle_pedido_id', sa.Integer(), nullable=False),
    sa.Column('opcion_modificador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detalle_pedido_id'], ['detalles_pedido.id'], ),
    sa.ForeignKeyConstraint(['opcion_modificador_id'], ['opciones_modificadores.id'], ),
    sa.PrimaryKeyConstraint('detalle_pedido_id', 'opcion_modificador_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_pedido_modificadores')
    op.drop_index(op.f('ix_detalles_pedido_id'), table_name='detalles_pedido')
    op.drop_table('detalles_pedido')
    op.drop_index(op.f('ix_transacciones_id'), table_name='transacciones')
    op.drop_table('transacciones')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_feedback_cliente_id'), table_name='feedback_cliente')
    op.drop_table('feedback_cliente')
    op.drop_index(op.f('ix_cuentas_id'), table_name='cuentas')
    op.drop_table('cuentas')
    op.drop_index(op.f('ix_variantes_producto_sku'), table_name='variantes_producto')
    op.drop_index(op.f('ix_variantes_producto_id'), table_name='variantes_producto')
    op.drop_table('variantes_producto')
    op.drop_table('producto_locales')
    op.drop_table('producto_grupo_modificador')
    op.drop_index(op.f('ix_mesas_id'), table_name='mesas')
    op.drop_table('mesas')
    op.drop_index(op.f('ix_zonas_id'), table_name='zonas')
    op.drop_table('zonas')
    op.drop_index(op.f('ix_usuarios_tipo_documento'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_telefono'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_numero_documento'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_opciones_modificadores_id'), table_name='opciones_modificadores')
    op.drop_table('opciones_modificadores')
    op.drop_index(op.f('ix_metodos_pago_local_id'), table_name='metodos_pago_local')
    op.drop_table('metodos_pago_local')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_locales_id'), table_name='locales')
    op.drop_table('locales')
    op.drop_index(op.f('ix_grupos_modificadores_id'), table_name='grupos_modificadores')
    op.drop_table('grupos_modificadores')
    op.drop_index(op.f('ix_centros_produccion_id'), table_name='centros_produccion')
    op.drop_table('centros_produccion')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_variables_css_tema_id'), table_name='variables_css_tema')
    op.drop_table('variables_css_tema')
    op.drop_table('rol_permisos')
    op.drop_index(op.f('ix_negocios_ruc'), table_name='negocios')
    op.drop_index(op.f('ix_negocios_id'), table_name='negocios')
    op.drop_table('negocios')
    op.drop_index(op.f('ix_temas_id'), table_name='temas')
    op.drop_table('temas')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_codigo'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
